# Generated by Django 5.2.15 on 2026-07-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class, e.g. 'bi-car-front'", max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('brand', models.CharField(blank=True, help_text="Maker/origin tag, used as a sidebar filter, e.g. 'Toyota' or 'Yoruba cuisine'", max_length=80)),
                ('image_url', models.URLField(blank=True, help_text='Link to a product image')),
                ('photo_credit', models.CharField(blank=True, help_text="Required for most Wikimedia Commons photos, e.g. 'Photo: Jane Doe / CC BY-SA 4.0'", max_length=200)),
                ('logo_url', models.URLField(blank=True, help_text='Link to the real brand/company logo, shown as a small badge')),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text="0-100 overall rating shown as a badge on the card, like a 'Versus score'")),
                ('pros', models.TextField(blank=True, help_text='One point per line')),
                ('cons', models.TextField(blank=True, help_text='One point per line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compare.category')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='compare.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, help_text="e.g. 'hp', 'GB', 'kcal'", max_length=30)),
                ('higher_is_better', models.BooleanField(default=True, help_text='Untick for specs where lower is better, e.g. price, weight')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='compare.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('votes_a', models.PositiveIntegerField(default=0)),
                ('votes_b', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='compare.category')),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='compare.item')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='compare.item')),
            ],
            options={
                'ordering': ['-views'],
                'unique_together': {('item_a', 'item_b')},
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(help_text="Display value, e.g. '200 hp' or 'Yes'", max_length=200)),
                ('value_numeric', models.FloatField(blank=True, help_text='Optional numeric value used to auto-highlight the winner', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='compare.item')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='compare.spec')),
            ],
            options={
                'unique_together': {('item', 'spec')},
            },
        ),
    ]
