# Generated by Django 5.2.15 on 2026-07-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_credit',
            field=models.CharField(blank=True, help_text="Required for most Wikimedia Commons photos, e.g. 'Photo: Jane Doe / CC BY-SA 4.0'", max_length=200),
        ),
    ]
